name: Deploy Pre-9roomthon (EC2 builds Docker)

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-pre-9roomthon-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      # build 대신 bootJar만 뽑아도 OK (둘 중 하나 선택)
      - name: Build Spring Boot JAR
        run: ./gradlew clean build -x test


      # 프로젝트 전체를 EC2로 복사 (불필요/민감 파일 제외)
      - name: Create .env file from single GitHub Secret
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Copy project to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          # 데이터/로그 보존 위해 rm 비활성화 (필요시 true로)
          rm: false
          source: "."
          target: "/home/${{ secrets.EC2_USER }}/pre-9roomthon"

      # EC2에서 .env 생성 → Docker Compose 빌드/배포
      - name: SSH into EC2 and run Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd pre-9roomthon
            docker compose down || true
            docker compose --env-file .env up -d --build

